repos:
  - repo: local
    hooks:
      - id: pytest
        name: Run pytest
        entry: pytest tests/
        language: system
        pass_filenames: false
        stages: [pre-commit]

      - id: commitizen
        name: Commitizen Check
        entry: cz check --commit-msg-file
        language: system
        stages: [commit-msg]